#!/bin/bash

# The docker compose file is in the currect repository
# under ".scripts/docker/confluentinc/" directory
SCRIPT_PATH="$(dirname -- "${BASH_SOURCE[0]}")"
cd $SCRIPT_PATH/../../
pwd

CREDENTIAL=$(aws sts get-session-token | jq .Credentials)
export AWS_ACCESS_KEY_ID=$(echo $CREDENTIAL | jq -r .AccessKeyId)
export AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIAL | jq -r .SecretAccessKey)
export AWS_SESSION_TOKEN=$(echo $CREDENTIAL | jq -r .SessionToken)

export CHECKPOINT_INERVAL=60000
export CHECKPOINT_TIMEOUT=3600000
export MAX_CONCURRENT_CHECKPOINTS=1

# S3 location
export CHECKPOINT_DIR="s3://huge-head-li-2023-glue-example/sink-checkpoints"

export BOOTSTRAP_SERVER="localhost:9093"
export SCHEMA_REGISTRY_URL="http://localhost:8081"
export GROUP_ID="TEST_GROUP"
export TOPIC_NAME="example-topic"

mvn clean test -Dtest="DynamoDBSinkJobTest"