#!/bin/bash

# This project use the docker-compose from the 
# https://github.com/BigMountainTiger/docker-common-examples.git

cd flink-checkpoint-example/
pwd

export SCHEMA_REGISTRY_URL="http://localhost:8081"
export TOPIC_NAME="example-topic"

mvn clean test -Dtest="DynamoDBSinkJobTest"