#!/bin/bash

# Check the docker-compose.yml for the URLs
BOOTSTRAP_SERVERS="localhost:9093"
SCHEMA_REGISTRY="http://localhost:8081"

TOPIC="avro-topic"

kafka-avro-console-consumer \
    --bootstrap-server $BOOTSTRAP_SERVERS \
    --property schema.registry.url=$SCHEMA_REGISTRY \
    --from-beginning \
    --topic $TOPIC
